name: WikiNarau CI

on:
  push:
  pull_request:

env:
  HUSKY: 0

jobs:
  test:
    runs-on: ubuntu-latest
    name: Typecheck
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --save-dev
      - name: Check types
        run: npm run check
