name: WikiNarau CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Typecheck
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --save-dev
      - name: Check types
        run: npm run check

  build-container:
    runs-on: ubuntu-latest
    name: Build docker image
    needs: test
    permissions:
      contents: read
      packages: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build docker image
        run: export DOCKER_BUILDKIT=1 && docker build -t wikinarau:${{ github.ref_name }} .
      - name: Tag image
        run: docker tag wikinarau:${{ github.ref_name }} ghcr.io/wikinarau/wikinarau:${{ github.ref_name }}
      - name: Push image
        run: docker push ghcr.io/wikinarau/wikinarau:${{ github.ref_name }}
